[package]
name = "acnhc-db"
version = "0.9.4"
authors = ["Fox Box <foxboxpdx@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"
serde = "1.0"
serde_derive = "1.0"
